#!/usr/bin/expect -f
set timeout -1
set password "Prasath@1990"
set ip "103.191.208.98"

spawn ssh -o StrictHostKeyChecking=no root@$ip "pm2 delete gurupriya_frontend; fuser -k 3006/tcp || true; fuser -k 3001/tcp || true; sleep 2; cd /var/www/gurupriyapyropark/frontend && pm2 start npm --name 'gurupriya_frontend' -- start -- -p 3006 && pm2 save"
expect {
    "password:" {
        send "$password\r"
        exp_continue
    }
    eof
}
puts "Complete."
